#!/usr/bin/env bash
set -euo pipefail

# Generate an auditable repository/module inventory for OPTKIT-001.
# Run from any directory; output defaults beside this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/../../../../../../.." && pwd)"
OUTPUT="${1:-$SCRIPT_DIR/../sources/01-repository-inventory.md}"
REPOS=(optkit ragkit ragopt judgekit coinvault rag-ttc)

mkdir -p "$(dirname "$OUTPUT")"
{
  echo '# Repository Inventory'
  echo
  echo "Generated by \`scripts/01-repository-inventory.sh\` on $(date --iso-8601=seconds)."
  echo
  echo '| Repository | HEAD | Module | Go files | Go lines | Go packages | Working tree |'
  echo '|---|---|---|---:|---:|---:|---|'
  for repo in "${REPOS[@]}"; do
    root="$WORKSPACE/$repo"
    head="$(git -C "$root" rev-parse --short=12 HEAD)"
    module="$(awk '$1 == "module" {print $2; exit}' "$root/go.mod")"
    go_files="$(find "$root" -name '*.go' -not -path '*/.git/*' -not -path '*/ttmp/*' | wc -l)"
    go_lines="$(find "$root" -name '*.go' -not -path '*/.git/*' -not -path '*/ttmp/*' -print0 | xargs -0 wc -l | tail -1 | awk '{print $1}')"
    packages="$(cd "$root" && GOWORK=off go list ./... | wc -l)"
    status="$(git -C "$root" status --porcelain | wc -l) changed paths"
    printf '| `%s` | `%s` | `%s` | %s | %s | %s | %s |\n' "$repo" "$head" "$module" "$go_files" "$go_lines" "$packages" "$status"
  done

  echo
  echo '## Product dependencies on the extracted kits'
  echo
  echo '| Product | FlowKit imports | JudgeKit imports | RagKit imports | RagOpt imports |'
  echo '|---|---:|---:|---:|---:|'
  for repo in coinvault rag-ttc; do
    counts=()
    for kit in flowkit judgekit ragkit ragopt; do
      count="$({ rg -l "github.com/go-go-golems/$kit" "$WORKSPACE/$repo" --glob '*.go' --glob '!ttmp/**' || true; } | wc -l)"
      counts+=("$count")
    done
    printf '| `%s` | %s | %s | %s | %s |\n' "$repo" "${counts[0]}" "${counts[1]}" "${counts[2]}" "${counts[3]}"
  done

  echo
  echo '## Supplied Optkit implementation archive'
  echo
  archive="$WORKSPACE/sources/optkit-implementation-source.zip"
  echo "- Archive: \`$archive\`"
  echo "- ZIP comment/revision: \`$(unzip -z "$archive" | tail -1)\`"
  echo "- Go files: $(unzip -l "$archive" | awk '$4 ~ /\.go$/ {n++} END {print n+0}')"
  echo "- Checked-out Optkit module: \`$(awk '$1 == "module" {print $2; exit}' "$WORKSPACE/optkit/go.mod")\`"
  echo '- Archive module: `github.com/go-go-golems/optkit`'
  echo '- The archive was tested after extraction; test evidence is recorded in the ticket diary.'
} > "$OUTPUT"

echo "$OUTPUT"
